- README.md
@pirog this adds some basic install instructions.
> Updating README.md with basic installation instructions.

- lib/app.js
- lib/metrics.js
- plugins/lando-core/index.js
- plugins/lando-core/lib/tasks/info.js
- plugins/lando-core/lib/urls.js
- plugins/lando-proxy/lib/proxy.js
- plugins/lando-services/lib/config.js
- plugins/lando-sharing/lib/sharing.js
> 10 refactor info

- examples/mysql/.lando.yml
- examples/mysql/config/my.cnf
- examples/mysql/www/50x.html
- examples/mysql/www/index.html
- plugins/lando-services/lib/bootstrap.js
- plugins/lando-services/mysql/mysql.js
> Issue #20: Adding mysql service.

- examples/lamp/.lando.yml
- examples/nginx/.lando.yml
- plugins/lando-services/apache/apache.js
- plugins/lando-services/lib/config.js
- plugins/lando-services/lib/services.js
- plugins/lando-services/mariadb/mariadb.js
- plugins/lando-services/mysql/mysql.js
- plugins/lando-services/nginx/nginx.js
- plugins/lando-services/php/php.js
> 13 delegated info

- examples/postgres/.lando.yml
- examples/postgres/config/postgresql.conf
- examples/postgres/www/50x.html
- examples/postgres/www/index.html
- plugins/lando-services/lib/bootstrap.js
- plugins/lando-services/postgres/postgres.js
> 18 postgres

- docs/SUMMARY.md
- docs/changelog/2017.md
- docs/cli/logs.md
- docs/cli/usage.md
- docs/config/services.md
- docs/dev/api/engine.md
- docs/services/memcached.md
- docs/services/solr.md
- docs/troubleshooting/logs.md
- examples/memcached/.gitignore
- examples/memcached/.lando.yml
- examples/memcached/app.js
- examples/memcached/package.json
- examples/node/package.json
- examples/solr/app.js
- examples/solr/package.json
- lib/compose.js
- lib/docker.js
- lib/engine.js
- plugins/lando-core/lib/tasks.js
- plugins/lando-core/lib/tasks/logs.js
- plugins/lando-services/lib/bootstrap.js
- plugins/lando-services/memcached/memcached.js
- plugins/lando-services/node/node.js
> 17 memcached

- examples/backdrop/.lando.yml
- examples/drupal7/.lando.yml
- examples/lamp/.lando.yml
- examples/lemp/.lando.yml
- examples/lemp2/.lando.yml
- examples/wordpress/.lando.yml
- plugins/lando-core/lib/env.js
- plugins/lando-recipes/backdrop/backdrop.js
- plugins/lando-recipes/drupal7/drupal7.js
- plugins/lando-recipes/lamp/lamp.js
- plugins/lando-recipes/wordpress/wordpress.js
- plugins/lando-services/apache/apache.js
- plugins/lando-services/lib/config.js
- plugins/lando-services/lib/services.js
- plugins/lando-services/nginx/nginx.js
- plugins/lando-services/node/node.js
- plugins/lando-services/php/php.js
- plugins/lando-services/scripts/user-perms.sh
- plugins/lando-services/scripts/webroot-chown.sh
- plugins/lando-sharing/scripts/sharing-usermap.sh
- plugins/lando-tooling/lib/tasks/ssh.js
- plugins/lando-tooling/lib/tooling.js
> #83: Lock down our docker side permissions

- docs/changelog/2017.md
- docs/config/services.md
- docs/installation/installing.md
- examples/backdrop/.gitignore
- examples/backdrop/.lando.yml
- examples/trivial-tooling/.lando.yml
- lib/container.js
- plugins/lando-services/php/5.3-apache/Dockerfile
- plugins/lando-services/php/5.3-apache/README.md
- plugins/lando-services/php/5.3-fpm/Dockerfile
- plugins/lando-services/php/5.3-fpm/README.md
- plugins/lando-services/php/5.5-apache/Dockerfile
- plugins/lando-services/php/5.5-apache/README.md
- plugins/lando-services/php/5.5-fpm/Dockerfile
- plugins/lando-services/php/5.5-fpm/README.md
- plugins/lando-services/php/5.6-apache/Dockerfile
- plugins/lando-services/php/5.6-apache/README.md
- plugins/lando-services/php/5.6-fpm/Dockerfile
- plugins/lando-services/php/5.6-fpm/README.md
- plugins/lando-services/php/7.0-apache/Dockerfile
- plugins/lando-services/php/7.0-apache/README.md
- plugins/lando-services/php/7.0-fpm/Dockerfile
- plugins/lando-services/php/7.0-fpm/README.md
- plugins/lando-services/php/7.1-apache/Dockerfile
- plugins/lando-services/php/7.1-apache/README.md
- plugins/lando-services/php/7.1-fpm/Dockerfile
- plugins/lando-services/php/7.1-fpm/README.md
- plugins/lando-services/scripts/user-perms.sh
> #85: Fix perm mapping and add some basic cli tools for php

- docs/recipes/wordpress.md
changed 'drupal' to 'WordPress'
> fix typo in wordpress.md

- docs/SUMMARY.md
- docs/changelog/2017.md
- docs/tutorials/external-access.md
- plugins/lando-core/lib/urls.js
- plugins/lando-recipes/lib/config.js
> 97 port forwarding

- docs/changelog/2017.md
- docs/config/services.md
- examples/backdrop/.lando.yml
- plugins/lando-recipes/drupal7/drupal7.js
- plugins/lando-recipes/drupal8/drupal8.js
- plugins/lando-recipes/wordpress/wordpress.js
- plugins/lando-services/lib/services.js
> 93 scripts

- docs/changelog/2017.md
- docs/cli/info.md
- examples/apache/index.html
- examples/solr/.lando.yml
- plugins/lando-core/lib/tasks/info.js
- plugins/lando-services/apache/apache.js
- plugins/lando-services/mariadb/mariadb.js
- plugins/lando-services/mysql/mysql.js
- plugins/lando-services/nginx/nginx.js
- plugins/lando-services/php/php.js
- plugins/lando-services/postgres/postgres.js
- plugins/lando-services/redis/redis.js
- plugins/lando-services/solr/solr.js
> 75 extra infoz

- docs/changelog/2017.md
- examples/node/.lando.yml
- examples/node/package.json
- plugins/lando-services/node/node.js
> #73: Make command usage clearer and more obvious for node services

- docs/SUMMARY.md
- docs/changelog/2017.md
- docs/config/services.md
- docs/services/varnish.md
- examples/memcached/app.js
- examples/redis/app.js
- examples/solr/app.js
- examples/varnish/.gitignore
- examples/varnish/.lando.yml
- examples/varnish/custom.vcl
- examples/varnish/index.php
- plugins/lando-services/lib/bootstrap.js
- plugins/lando-services/varnish/ssl-termination.conf
- plugins/lando-services/varnish/varnish.js
> #62: Add varnish service

- docs/installation/installing.md
The `From Source` section includes a note and warning regarding node installation.
> Add note to install node in installing.md

- docs/changelog/2017.md
- examples/pantheon/.lando.yml
- plugins/lando-recipes/pantheon/pantheon.js
- plugins/lando-services/scripts/user-perms.sh
> 132 pantheon php

- docs/SUMMARY.md
- docs/tutorials/frontend.md
> 143 front end docs

- lib/cli.js
> Fix typo on lando start

- plugins/lando-recipes/pantheon/mysql/my.cnf
- [✅ ] My code passes relevant CI status checks
-----
Yoooo not sure how this would be documented in the changelog, since it looks like its release dependent. Happy to resubmit this PR if that's a problem. Thanks!
> Fix for kalabox/lando#182:

- docs/README.md
> Change from land to lando

- docs/installation/uninstalling.md
> Change Mac to Windows in Windows section

- docs/issues/file-sync.md
> Grammar change from have to has

- docs/tutorials/recipe-config.md
> Grammar change lets to let's

- docs/tutorials/ast.md
> Remove .dev to avoid confusion

- docs/config/lando.md
> Remove that

- docs/recipes/wordpress.md
> Grammar changes to WordPress page

- docs/config/proxy.md
> Grammar corrections

- docs/config/config.md
> Grammar changes to config.yml section

- docs/recipes/backdrop.md
> Grammar changes to Backdrop page

- docs/recipes/drupal6.md
> Grammar changes to Drupal 6 page

- docs/recipes/drupal7.md
> Grammar changes to Drupal 7 page

- docs/recipes/drupal8.md
> Grammar changes to Drupal 8 page

- docs/recipes/laravel.md
> Grammar changes to Laravel page

- docs/recipes/lamp.md
> Grammar changes to LAMP page

- docs/recipes/lemp.md
> Grammar changes to LEMP page

- docs/services/apache.md
> Grammar changes to Apache page

- docs/services/mariadb.md
> Grammar changes to MariaDB page

- docs/services/memcached.md
> Grammar changes to Memcached page

- docs/services/mailhog.md
> Grammar changes to MailHog page

- docs/services/elasticsearch.md
> Grammar changes to Elasticsearch page

- docs/recipes/pantheon.md
> Grammar changes to Pantheon page

- docs/services/nginx.md
> Grammar changes to nginx page

- docs/services/mysql.md
> Grammar changes to MySQL page

- docs/services/node.md
> Grammar changes to node page

- docs/services/php.md
> Grammar changes to php page

- docs/services/phpmyadmin.md
> Grammar changes to phpMyAdmin page

- docs/services/postgres.md
> Grammar changes to PostgreSQL page

- docs/services/redis.md
> Grammar changes to Redis page

- docs/services/varnish.md
> Grammar changes to Varnish page

- docs/services/solr.md
> Grammar changes to Solr page

- docs/changelog/2017.md
- docs/installation/installing.md
- docs/issues/file-sync.md
- lib/compose.js
- lib/config.js
- lib/docker.js
- lib/engine.js
- plugins/lando-core/lib/init.js
- plugins/lando-services/lib/config.js
- plugins/lando-services/scripts/user-perms.sh
- plugins/lando-tooling/lib/tasks/ssh.js
- plugins/lando-tooling/lib/tooling.js
- tasks/shell.js
> 181 windoze fixez

- docs/changelog/2017.md
- lib/utils.js
- plugins/lando-core/lib/services.js
- plugins/lando-proxy/lib/bootstrap.js
- plugins/lando-proxy/lib/proxy.js
- plugins/lando-recipes/lib/config.js
- plugins/lando-services/lib/config.js
- plugins/lando-services/lib/services.js
> #228: Fixed build steps and extras to concatenate

- docs/SUMMARY.md
- docs/changelog/2017.md
- docs/cli/share.md
- lib/cli.js
- plugins/lando-core/lib/bootstrap.js
- plugins/lando-core/lib/tasks/share.js
> #84: Lando share command

- docs/changelog/2017.md
- plugins/lando-core/lib/tasks/init.js
> #243: Fix lando init merge to rebase on preexisting lando.yml

- docs/changelog/2017.md
- lib/engine.js
- lib/node.js
- package.json
- plugins/lando-proxy/lib/proxy.js
- plugins/lando-recipes/pantheon/pull.sh
- plugins/lando-services/php/php.js
> 231 xdebug take2

- docs/changelog/2017.md
- docs/tutorials/pantheon.md
- plugins/lando-recipes/pantheon/pantheon.js
- plugins/lando-recipes/pantheon/pull.sh
> #240: Make lando pull more robust

- docs/tutorials/setup-additional-services.md
- docs/tutorials/setup-additional-tooling.md
- docs/tutorials/wordpress.md
> Minor documentation tweaks.

- docs/changelog/2017.md
- docs/tutorials/pantheon.md
- plugins/lando-recipes/pantheon/pantheon.js
- plugins/lando-recipes/pantheon/push.sh
> 239 pantheon push

- README.md
- docs/README.md
- docs/changelog/2017.md
- docs/dev/api/node.md
- docs/tutorials/backdrop.md
- docs/tutorials/drupal6.md
- docs/tutorials/drupal7.md
- docs/tutorials/drupal8.md
- docs/tutorials/lamp.md
- docs/tutorials/laravel.md
- docs/tutorials/lemp.md
- docs/tutorials/pantheon.md
- docs/tutorials/wordpress.md
- plugins/lando-recipes/pantheon/pantheon.js
- plugins/lando-recipes/pantheon/pull.sh
- plugins/lando-recipes/pantheon/push.sh
- plugins/lando-recipes/pantheon/switch.sh
> #241: Added lando switch command for pantheon multidev workflowz

- docs/changelog/2017.md
- plugins/lando-recipes/pantheon/client.js
- plugins/lando-recipes/pantheon/pantheon.js
- plugins/lando-recipes/pantheon/pull.sh
- plugins/lando-recipes/pantheon/push.sh
- plugins/lando-recipes/pantheon/switch.sh
- plugins/lando-tooling/lib/tooling.js
> #249: Pantheon utility commands are now interactive

- docs/changelog/2017.md
- docs/services/php.md
- examples/hhvm/.gitignore
- examples/hhvm/.lando.yml
- examples/hhvm/index.php
- plugins/lando-services/php/default.conf
- plugins/lando-services/php/php.js
> #67: Add hhvm option to php service

- docs/SUMMARY.md
> Fix typo in SUMMARY.md

- docs/SUMMARY.md
- docs/changelog/2017.md
- docs/config/services.md
- docs/services/ruby.md
- examples/ruby/.gitignore
- examples/ruby/.lando.yml
- examples/ruby/server.rb
- plugins/lando-services/lib/bootstrap.js
- plugins/lando-services/ruby/ruby.js
> #68: Added basic ruby service

- docs/changelog/2017.md
- lib/utils.js
- plugins/lando-recipes/pantheon/pull.sh
- plugins/lando-recipes/pantheon/push.sh
> Kalabox trans

- docs/recipes/backdrop.md
- docs/recipes/drupal6.md
- docs/recipes/drupal7.md
- docs/recipes/drupal8.md
- docs/recipes/joomla.md
- docs/recipes/lamp.md
- docs/recipes/laravel.md
- docs/recipes/lemp.md
- docs/recipes/mean.md
- docs/recipes/pantheon.md
- docs/recipes/wordpress.md
- docs/tutorials/backdrop.md
- docs/tutorials/drupal6.md
- docs/tutorials/drupal7.md
- docs/tutorials/drupal8.md
- docs/tutorials/joomla.md
- docs/tutorials/lamp.md
- docs/tutorials/laravel.md
- docs/tutorials/lemp.md
- docs/tutorials/mean.md
- docs/tutorials/pantheon.md
- docs/tutorials/wordpress.md
> Minor documentation changes for clarity

- docs/tutorials/lando-pantheon-workflow.md
> Use service names for Behat config.

- plugins/lando-services/php/5.3-apache/Dockerfile
- plugins/lando-services/php/5.3-apache/README.md
- plugins/lando-services/php/5.3-fpm/Dockerfile
- plugins/lando-services/php/5.3-fpm/README.md
- plugins/lando-services/php/5.4-apache/Dockerfile
- plugins/lando-services/php/5.4-apache/README.md
- plugins/lando-services/php/5.4-fpm/Dockerfile
- plugins/lando-services/php/5.4-fpm/README.md
- plugins/lando-services/php/5.5-apache/Dockerfile
- plugins/lando-services/php/5.5-apache/README.md
- plugins/lando-services/php/5.5-fpm/Dockerfile
- plugins/lando-services/php/5.5-fpm/README.md
- plugins/lando-services/php/5.6-apache/Dockerfile
- plugins/lando-services/php/5.6-apache/README.md
- plugins/lando-services/php/5.6-fpm/Dockerfile
- plugins/lando-services/php/5.6-fpm/README.md
- plugins/lando-services/php/7.0-apache/Dockerfile
- plugins/lando-services/php/7.0-fpm/Dockerfile
- plugins/lando-services/php/7.0-fpm/README.md
- plugins/lando-services/php/7.1-apache/Dockerfile
- plugins/lando-services/php/7.1-apache/README.md
- plugins/lando-services/php/7.1-fpm/Dockerfile
- plugins/lando-services/php/7.1-fpm/README.md
I'm unsure if CHANGELOG should include updates when composer is updated. But in an effort to get the exif stuff working with the current dockerfiles, composer hash needs to be updated first before the images can build.
> Update dockerfiles with new hash for composer.

- docs/recipes/drupal8.md
Page not found link: https://github.com/lando/lando/tree/master/examples/drupal8-2 
Correct link: https://github.com/lando/lando/tree/master/examples/drupal8
> Example .lando.yml full code link goes to page not found.

- docs/tutorials/offline-dev.md
> Document offline development with DNSMasq on OSX

- docs/changelog/2017.md
- docs/installation/installing.md
Documents some issues that through me for a loop while installing Lando from source.
> adds troubleshooting for Linux

- plugins/lando-services/php/5.3-apache/Dockerfile
- plugins/lando-services/php/5.3-fpm/Dockerfile
- plugins/lando-services/php/5.4-apache/Dockerfile
- plugins/lando-services/php/5.4-fpm/Dockerfile
- plugins/lando-services/php/5.5-apache/Dockerfile
- plugins/lando-services/php/5.5-fpm/Dockerfile
- plugins/lando-services/php/5.6-apache/Dockerfile
- plugins/lando-services/php/5.6-fpm/Dockerfile
- plugins/lando-services/php/7.0-apache/Dockerfile
- plugins/lando-services/php/7.0-fpm/Dockerfile
- plugins/lando-services/php/7.1-apache/Dockerfile
- plugins/lando-services/php/7.1-fpm/Dockerfile
This PR adds exiftool and php-exif to the php service containers (since pantheon offers exif).
I'm unsure if I should be adding anything to the CHANGELOG file.
> Add exif to php service.

- docs/config/env.md
> Fix broken link in env.md

- docs/config/build.md
> Update internal link in docs.

- docs/tutorials/backdrop.md
- docs/tutorials/drupal6.md
- docs/tutorials/drupal7.md
- docs/tutorials/drupal8.md
- docs/tutorials/wordpress.md
> Issue #378: Confusion On Drupal 8 Install With Database Import

- docs/recipes/drupal7.md
- docs/recipes/drupal8.md
- docs/recipes/pantheon.md
> info on fixing file uploads in Drupal

- docs/tutorials/drupal7.md
Adds extra information concerning aliases in Lando in a drupal 7 environment.
> Update drush section Drupal7.md

- docs/changelog/2017.md
- installer/linux/scripts/postrm
- installer/osx/uninstall.sh
> User config should not be removed during uninstall

- docs/tutorials/frontend.md
build command appears to be indented incorrectly, I've updated the relevant lines
- [ n/a] My code passes relevant CI status checks
- [ n/a] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [ n/a] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [ x] My code includes documentation updates if relevant.
- [ n/a] I have pinged @pirog/@reynoldsalec/@serundeputy when I think my code is ready for …
> [docs] update indenting in `build` section

- docs/tutorials/pantheon.md
@pirog Very minor edit to remove personal dev site info, thanks for this example, very helpful!
> remove reference to personal dev site

- docs/changelog/2017.md
- plugins/lando-recipes/pantheon/pantheon.sh
> #481: Better tmp directory handling for pantheon recipes

- docs/troubleshooting/wkbox.md
Additional note about how running Docker may auto start Kalabox containers before starting Kalabox.
> Update docs for using Lando with Kalabox

- README.md
- docs/started.md
This should help people not fall into the trap of #520.
> Clarify Lando docs

- docs/tutorials/offline-dev.md
> Developing offline not working. #448

- .travis.yml
- docs/changelog/2017.md
- scripts/build-osx.sh
> First pass on codesigning macOS pkg

- docs/_layouts/layout.html
> Add in adsense snippet

- docs/tutorials/wordpress.md
Correct "Accessing Services" link
- [ x ] My code is just a doc update
> Doc-only: Correct "Accessing Services" link

- docs/tutorials/wordpress.md
Missing `lando` command in example.
- [ x] This is just a doc update
> Doc-only: Update wordpress.md

- docs/config/files.md
> Issue #548: Broken Link On Shared Files

- docs/tutorials/pantheon.md
Taken from http://starwars.wikia.com/wiki/Wookieepedia:Quote_of_the_Day/Archive/Lando_Calrissian
Originally Lando: "That won't be easy, my friend."
> better commit message

- plugins/lando-services/scripts/lando-entrypoint.sh
> Fix Bug: Containers for memcache and solr fail to start #437

- docs/config/proxy.md
> Issue #613: Add Debug Info To Proxy Help

- lib/metrics.js
- lib/update.js
> #630 Fix no internet connectivity bug while gathering update info

- Gruntfile.js
- docs/changelog/2018.md
- docs/config/lando.md
Addresses #643. No code changes, just comments and markdown.
> 643 document .lando.yml syntax more explicitly

- docs/config/scripting.md
Fix typo in sevices to services.
> Fix typo in services word.

- lib/config.js
- lib/lando.js
- package.json
- yarn.lock
> Downgrade fs-extra for better electron asar compat

- README.md
> Fixed broken link to the recipes doc

- lib/cache.js
- package.json
- test/events.spec.js
- yarn.lock
> Closes #638

- .circleci/config.yml
- .travis.yml
- docs/api/api.md
- docs/changelog/2018.md
- docs/contrib/contributing.md
- docs/dev/testing.md
- lib/config.js
- package.json
- plugins/lando-app/tasks/list.js
- plugins/lando-app/test/.eslintrc.json
- plugins/lando-app/test/functional/cli/app.spec.js
- plugins/lando-core/test/.eslintrc.json
- plugins/lando-core/test/functional/cli/basic-usage.spec.js
- plugins/lando-init/test/functional/cli/init.spec.js
- plugins/lando-tooling/test/functional/cli/tooling.spec.js
- test/unit/cache.spec.js
- test/unit/config.spec.js
- test/unit/events.spec.js
- yarn.lock
This PR is a first pass of our functional testing suite. I am recommending we get this into master soon to help provide a general pattern for functional testing to improve our bug remediation process. We should now be able to generally follow the pattern of these tests to document, reproduce, fix, and verify the fix for nearly all reported bugs. @pirog, @serundeputy, please review, thanks!
> Closes #675

- docs/SUMMARY.md
- docs/changelog/2018.md
- plugins/lando-init/init.js
- plugins/lando-init/methods/github.js
- plugins/lando-recipes/recipes/pantheon/init.js
> #178: Improved speed of lando init method drive git clone

- plugins/lando-services/services/mariadb/mariadb.js
- plugins/lando-services/services/mysql/mysql.js
- plugins/lando-services/services/postgres/postgres.js
> Fix manifest build thing

- examples/mysql/.lando.yml
> do the thing that the docs are say it is doing

- bin/lando.js
- lib/config.js
- lib/yaml.js
- test/unit/config.spec.js
- test/unit/yaml.spec.js
> 788 unit test yaml

- docs/changelog/2018.md
- lib/cache.js
- plugins/lando-engine/index.js
- plugins/lando-init/methods/github.js
- plugins/lando-recipes/recipes/pantheon/client.js
- plugins/lando-recipes/recipes/pantheon/init.js
- plugins/lando-recipes/recipes/pantheon/pantheon.js
- plugins/lando-services/index.js
- test/unit/cache.spec.js
- yarn.lock
@pirog ready for review and hopefully mergy mergy!
> 802 unit test cache

- .travis.yml
- docs/changelog/2018.md
- docs/installation/installing.md
- scripts/build-linux.sh
- scripts/env.sh
- scripts/install-deps.sh
> #814: Add Arch-based distro pacman package build support

- docs/changelog/2018.md
- plugins/lando-app/app.js
- plugins/lando-engine/engine.js
- plugins/lando-engine/lib/utils.js
- plugins/lando-events/index.js
- plugins/lando-init/init.js
- plugins/lando-init/methods/github.js
- plugins/lando-recipes/index.js
- plugins/lando-recipes/recipes/pantheon/init.js
- plugins/lando-services/index.js
- plugins/lando-services/lib/utils.js
- plugins/lando-services/services.js
- plugins/lando-tooling/tasks/ssh.js
- plugins/lando-tooling/tooling.js
> #829 #697: Improve app name parsing

- scripts/build-linux.sh
- scripts/build-pkg.sh
- scripts/env.sh
- scripts/install-deps.sh
> #814: Fixup pacman version syntax restrictions

- lib/tasks.js
- test/unit/tasks.spec.js
Easiest test PR ever.
This module IMO could use some improvements. It doesn't validate the task object from what I can tell, there is only a single method and I don't think it needs much more coverage than this single spec for now.
> 785 unit test tasks

- docs/changelog/2018.md
- scripts/env.sh
> Correct licence used when packaging application

- docs/tutorials/pantheon.md
Added bits that should clear up any confusion about `lando pull` not doing the initial `git clone ...` for users.
> Updated Pantheon recipe to call out `git clone` pre-step

- docs/issues/switching-dbs.md
> destrou -> destroy

- docs/tutorials/drupal7.md
Re: https://github.com/lando/lando/issues/918
> Adding port number to base_url instructions

- plugins/lando-recipes/recipes/pantheon/client.js
Quick fix to a bug reported by users in Slack. Pantheon's API seems to have changed.
> Fixes #922

- examples/drupal7/config/mysql/my.cnf
- examples/lamp2/config/mysql/my.cnf
- examples/lemp/config/mysql/my.cnf
- examples/mariadb/config/my.cnf
- plugins/lando-recipes/recipes/backdrop/mysql/my.cnf
- plugins/lando-recipes/recipes/drupal6/mysql/my.cnf
- plugins/lando-recipes/recipes/drupal7/mysql/my.cnf
- plugins/lando-recipes/recipes/drupal8/mysql/my.cnf
- plugins/lando-recipes/recipes/joomla/mysql/my.cnf
- plugins/lando-recipes/recipes/laravel/mysql/my.cnf
- plugins/lando-recipes/recipes/pantheon/mysql/my.cnf
- plugins/lando-recipes/recipes/wordpress/mysql/my.cnf
---
I have not pinged a maintainer, nor have I included tests or updated the CHANGELOG. I simply wanted to point out a typo. I'd be happy to provide any more if necessary. 
This isn't urgent and does not affect functionality, but I found a typo and thought I'd try to help with it. Sorry if this wasn't the correct process. Thanks for this amazing tool!
> Found a typo in my.cnf files

- docs/tutorials/drupal8.md
Unsurprisingly, Drupal 8's recipe specified drupal8 as the user, password and database name.
> Docs update: Correcting error in database credentials

- docs/changelog/2018.md
- plugins/lando-recipes/recipes/laravel/laravel.js
@pirog this should be all set, overridden the Pantheon way™
> #958 Inject App Log

- docs/config/advanced.md
> Clarify LANDOFILE

- lib/config.js
- plugins/lando-engine/test/unit/env.spec.js
- plugins/lando-services/lib/utils.js
- plugins/lando-services/services.js
- plugins/lando-services/test/unit/utils.spec.js
> Windoze normalize

- plugins/lando-recipes/recipes/pantheon/pull.sh
Just using the domain will replace URLs properly and allow for `http` and `https`.
> Don't hard code http in search/replace

- book.json
- docs/tutorials/backdrop.md
> Youtube vids in gitbook

- plugins/lando-services/helpers/sql-import.sh
> Replace gunzip with gzip

- examples/solr/.lando.yml
> Adds clarifying sentence for solr configuration.

- plugins/lando-app/tasks/poweroff.js
> resolves flow control issue by returning from promise.

- docs/config/proxy.md
> docs typo fix

- docs/tutorials/laravel.md
Specifies what key value pairs in the .env file are important to change for a working Laravel project with Lando.
> #1116: add instructions for local laravel env

- plugins/lando-services/services/php/5.3-apache/Dockerfile
- plugins/lando-services/services/php/5.3-apache/README.md
- plugins/lando-services/services/php/5.3-fpm/Dockerfile
- plugins/lando-services/services/php/5.3-fpm/README.md
- plugins/lando-services/services/php/5.4-apache/Dockerfile
- plugins/lando-services/services/php/5.4-apache/README.md
- plugins/lando-services/services/php/5.4-fpm/Dockerfile
- plugins/lando-services/services/php/5.4-fpm/README.md
- plugins/lando-services/services/php/5.5-apache/Dockerfile
- plugins/lando-services/services/php/5.5-apache/README.md
- plugins/lando-services/services/php/5.5-fpm/Dockerfile
- plugins/lando-services/services/php/5.5-fpm/README.md
- plugins/lando-services/services/php/5.6-apache/Dockerfile
- plugins/lando-services/services/php/5.6-apache/README.md
- plugins/lando-services/services/php/5.6-fpm/Dockerfile
- plugins/lando-services/services/php/5.6-fpm/README.md
- plugins/lando-services/services/php/7.0-apache/Dockerfile
- plugins/lando-services/services/php/7.0-apache/README.md
- plugins/lando-services/services/php/7.0-fpm/Dockerfile
- plugins/lando-services/services/php/7.0-fpm/README.md
- plugins/lando-services/services/php/7.1-apache/Dockerfile
- plugins/lando-services/services/php/7.1-apache/README.md
- plugins/lando-services/services/php/7.1-fpm/Dockerfile
- plugins/lando-services/services/php/7.1-fpm/README.md
- plugins/lando-services/services/php/7.2-apache/Dockerfile
- plugins/lando-services/services/php/7.2-apache/README.md
- plugins/lando-services/services/php/7.2-fpm/Dockerfile
- plugins/lando-services/services/php/7.2-fpm/README.md
> Make sure GD is compiled with freetype

- docs/_layouts/website/page.html
@pirog @dustinleblanc this adds a font-awesome youtbube icon linking to the youtube channel in the header next to the github icon to encourage subscriptions.
yea or nay?
> Adding link to youtube channel; fix header logo to link to docs home.

- .platform/routes.yaml
> Remove https

- plugins/lando-engine/lib/compose.js
- plugins/lando-engine/lib/docker.js
- plugins/lando-engine/lib/router.js
- plugins/lando-networking/index.js
- plugins/lando-networking/scripts/add-cert.sh
- plugins/lando-networking/scripts/refresh-certs.sh
- plugins/lando-recipes/recipes/pantheon/pantheon.js
- plugins/lando-recipes/recipes/pantheon/pull.sh
- plugins/lando-recipes/recipes/pantheon/push.sh
- plugins/lando-services/services/nginx/nginx.js
- plugins/lando-services/services/solr/solr.js
- plugins/lando-services/services/varnish/varnish.js
> #822: Update pantheon for RC1 readiness

- plugins/lando-engine/lib/compose.js
- plugins/lando-engine/lib/router.js
- plugins/lando-engine/scripts/load-keys.sh
- plugins/lando-engine/test/unit/compose.spec.js
- plugins/lando-recipes/recipes/pantheon/init.js
- scripts/build-linux.sh
- scripts/build-win32.ps1
> Update lin win

- examples/wordpress/README.md
- examples/wordpress/config/wp-config.php
Failed on `pma` tests, but `wordpress` tests look good.
https://circleci.com/gh/lando/lando/625#usage-queue/containers/3
> Adding functional tests for the WordPress recipe.

- docs/config/security.md
Updating the docs so that the commands for trusting the default certificate are up to date with the latest changes in RC1.
> Update security.md with the new certificate

- docs/SUMMARY.md
- docs/_layouts/website/page.html
- docs/css/styles.css
- docs/jobs/2018-full-stack-dev.md
@pirog here's the docs modifications that I'm suggesting to notify people about the open gig.
> Job opportunity notification

- docs/tutorials/pantheon.md
> Revert "Updated Pantheon recipe to call out `git clone` pre-step"

- docs/changelog/2018.md
- examples/pantheon/README.md
- plugins/lando-recipes/recipes/pantheon/5.3-fpm/Dockerfile
- plugins/lando-recipes/recipes/pantheon/5.3-fpm/README.md
- plugins/lando-recipes/recipes/pantheon/5.5-fpm/Dockerfile
- plugins/lando-recipes/recipes/pantheon/5.5-fpm/README.md
- plugins/lando-recipes/recipes/pantheon/5.6-fpm/Dockerfile
- plugins/lando-recipes/recipes/pantheon/5.6-fpm/README.md
- plugins/lando-recipes/recipes/pantheon/7.0-fpm/Dockerfile
- plugins/lando-recipes/recipes/pantheon/7.0-fpm/README.md
- plugins/lando-recipes/recipes/pantheon/7.1-fpm/Dockerfile
- plugins/lando-recipes/recipes/pantheon/7.1-fpm/README.md
- plugins/lando-recipes/recipes/pantheon/7.2-fpm/Dockerfile
- plugins/lando-recipes/recipes/pantheon/7.2-fpm/README.md
Fixes #1260
Still waiting for `yarn test:functional` to run.
Assuming you have CI set up for PRs?
If not, will post with test output.
> Update Terminus to v1.9.0

- docs/tutorials/lando-with-vscode.md
> Update VS Code tutorial with PhpUnit debugging

- docs/tutorials/lando-with-vscode.md
> Use correct comment style in php.ini, fixes #1337.

- .circleci/config.yml
- docs/changelog/2019.md
- docs/guides/updating-to-rc2.md
- examples/node/README.md
- examples/pantheon/README.md
- examples/pantheon/remove-keys.sh
- lib/art.js
- lib/cli.js
- lib/compose.js
- lib/daemon.js
- lib/env.js
- plugins/lando-core/compose/lando/builder.js
- plugins/lando-core/scripts/load-keys.sh
> Final countdown

- .gitignore
- docs/changelog/2019.md
- docs/config/services.md
- docs/guides/updating-to-rc2.md
- examples/base/.lando.yml
- examples/base/README.md
- examples/base/info.php
- examples/drupal8/README.md
- examples/postgres/.lando.yml
- examples/postgres/README.md
- examples/tooling/.lando.yml
- examples/tooling/README.md
- plugins/lando-core/app.js
- plugins/lando-pantheon/lib/utils.js
- plugins/lando-pantheon/recipes/pantheon/mysql.cnf
- plugins/lando-recipes/lib/utils.js
- plugins/lando-recipes/recipes/backdrop/builder.js
- plugins/lando-recipes/recipes/backdrop/mysql.cnf
- plugins/lando-recipes/recipes/drupal6/mysql.cnf
- plugins/lando-recipes/recipes/drupal7/mysql.cnf
- plugins/lando-recipes/recipes/drupal8/mysql.cnf
- plugins/lando-recipes/recipes/joomla/mysql.cnf
- plugins/lando-recipes/recipes/laravel/mysql.conf
- plugins/lando-recipes/recipes/wordpress/builder.js
- plugins/lando-recipes/recipes/wordpress/mysql.conf
- plugins/lando-recipes/types/drupaly/builder.js
- plugins/lando-services/services/postgres/builder.js
- plugins/lando-tooling/lib/build.js
- plugins/lando-tooling/lib/utils.js
- scripts/build-releases-appveyor.ps1
> Pirog5000 hyperion

- docs/changelog/2019.md
- plugins/lando-pantheon/lib/utils.js
- plugins/lando-services/services/apache/builder.js
- plugins/lando-services/services/elasticsearch/builder.js
- plugins/lando-services/services/memcached/builder.js
- plugins/lando-services/services/mongo/builder.js
- plugins/lando-services/services/nginx/builder.js
- plugins/lando-services/services/varnish/builder.js
> Pirog5004 hyperion

- docs/config/lando.md
looking at 
https://github.com/lando/lando/blob/27974092c6c34d4505045111d9bc694ee641dee0/lib/cli.js#L151-L152
i think the docs are wrong, this fixes it :)
> Fix "Landofile" docs

- docs/guides/updating-to-rc2.md
> Followup to #1390: old syntax for overrides has services key

- docs/changelog/2019.md
- lib/compose.js
- plugins/lando-tooling/lib/utils.js
> #904: Improve TTY detection and passthru

- docs/changelog/2019.md
- examples/pantheon/README.md
- plugins/lando-core/scripts/load-keys.sh
- plugins/lando-pantheon/recipes/pantheon/builder.js
- plugins/lando-pantheon/scripts/auth.sh
- plugins/lando-pantheon/scripts/binding.sh
- plugins/lando-pantheon/scripts/pantheon.sh
- plugins/lando-recipes/types/laemp/builder.js
> Solr windoze lockr

- docs/changelog/2019.md
- docs/tutorials/dotnet.md
- plugins/lando-services/services/dotnet/builder.js
> #1325: Added support to run on non port 80 things to dotnet

- docs/changelog/2019.md
- docs/config/events.md
- examples/events/.lando.yml
- examples/events/compose.yml
- examples/sql-import/.lando.yml
- plugins/lando-events/lib/utils.js
> Provide better default service discovery for events

- docs/changelog/2019.md
- docs/guides/updating-to-rc2.md
> #1445 upgrade document hyphens

- docs/config/services.md
> #1443: Update example run_as_root command

- docs/README.md
> Fix broken updating-to-rc2 link.

- lib/app.js
- lib/shell.js
- plugins/lando-recipes/lib/build.js
- plugins/lando-services/app.js
- test/shell.spec.js
> Pld considerations

- docs/dev/testing.md
- [-] My code includes documentation updates if applicable.
> Typo: '..what's the catch?' 1... "frmo" to "from"

- docs/config/env.md
> Fixing a minor grammatical error

- plugins/lando-recipes/recipes/joomla/builder.js
- plugins/lando-recipes/recipes/laravel/builder.js
- plugins/lando-recipes/recipes/wordpress/builder.js
- plugins/lando-recipes/types/drupaly/builder.js
- plugins/lando-recipes/types/laemp/builder.js
> #1454: Consolidate default config setting for lampy things

- docs/cli/ssh.md
> Ensure that vim installation example actually works

- docs/config/services.md
- docs/tutorials/drupal7.md
- docs/tutorials/drupal8.md
> Add a note about using ~ in services scripts + update related examples.

- lib/logger.js
- [Y ] My code includes the latest code from the `master` branch
- [N ] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/changelog)
- [N ] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) …
> Update max log file size down to 500Mb each

- docs/config/events.md
> Docs: Update broken links in events.md

- docs/config/tooling.md
Here I suggest a minor improvement of the docs. I am open for all feedback.
> Documentation on Tooling: Improved 1st example, e.g. PHP parameter -r

- docs/config/tooling.md
> Fix build steps path.

- docs/guides/lando-with-vscode.md
> remote_port should be 9000 not 900

- docs/tutorials/drupal7.md
- docs/tutorials/drupal8.md
Docs lead to errors, very confusing.
As described in 
#https://github.com/lando/lando/issues/1525
#https://github.com/lando/lando/issues/1400
- [ x ] My code includes the latest code from the `master` branch
- [ x ] My code includes documentation updates if applicable.
> Following docs leads to error: TypeError: Invalid Version: 7.0

- package.json
- yarn.lock
This will fix this error: https://github.com/lando/lando/issues/1255#issuecomment-471004700
> Update PKG dependency to 4.3.7

- docs/tutorials/drupal7.md
Adding additional information for connecting to a postgres database instance, since the docs aren't too clear about postgres credentials. Hopefully will save people from a ton of headaches and Googling.
> Updating D7 docs, connecting with postgres

- docs/changelog/2019.md
- docs/config/security.md
- docs/config/services.md
- docs/guides/offline-dev.md
- docs/tutorials/node.md
- docs/tutorials/pantheon.md
- docs/tutorials/php.md
- plugins/lando-core/index.js
> Pirog rc16

- docs/changelog/2019.md
- docs/tutorials/drupal6.md
- docs/tutorials/drupal7.md
- docs/tutorials/drupal8.md
- examples/backdrop/README.md
- examples/drupal6/README.md
- examples/drupal7/README.md
- examples/drupal8/README.md
- examples/keys/.lando.yml
- examples/keys/README.md
- lib/cli.js
- lib/config.js
- plugins/lando-core/scripts/load-keys.sh
- plugins/lando-pantheon/lib/utils.js
- plugins/lando-recipes/recipes/backdrop/builder.js
- plugins/lando-recipes/types/drupaly/builder.js
> Pirog rc16 2

- plugins/lando-services/services/mariadb/builder.js
Fixes #1603 (I think). Not sure what else needs to change to add support.
Checklist:
> #1603: Add MariaDB 10.3 support

- docs/changelog/2019.md
- lib/docker.js
- plugins/lando-core/app.js
- plugins/lando-core/index.js
- plugins/lando-core/tasks/info.js
- plugins/lando-networking/app.js
- plugins/lando-services/app.js
- plugins/lando-services/services/postgres/builder.js
> #1612: Fix breaking upstream postgres change

- docs/tutorials/backdrop.md
- docs/tutorials/drupal6.md
- docs/tutorials/drupal7.md
- docs/tutorials/drupal8.md
- docs/tutorials/joomla.md
- docs/tutorials/lamp.md
- docs/tutorials/laravel.md
- docs/tutorials/lemp.md
- docs/tutorials/wordpress.md
For #1564, this puts quotes around the version number. It uses single quotes, which was already used in docs in another place for the php version.
This only appeared in tutorials. Before:
```
me@my-place:~/src/lando/docs$ grep -rn "php: [0-9]"
tutorials/backdrop.md:52:  php: 7.2 …
```
> Quote php version numbers in tutorials.

- docs/config/events.md
> Fixed typo on Events docs page

- docs/changelog/2019.md
- examples/apache/.lando.yml
- examples/apache/README.md
- examples/apache/config/custom.conf
- examples/apache/config/httpd.conf
- plugins/lando-core/scripts/add-cert.sh
- plugins/lando-services/services/apache/builder.js
- plugins/lando-services/services/apache/default-ssl.conf
> Update lando to handle breaking changes in apache bitnami images

- docs/config/security.md
> #1625: Docs for trusting certificate store in Firefox

- docs/config/security.md
> Fix Link to Networking in Security Page

- docs/guides/frontend.md
> Fixed reference to non-existent "`run` section"

- docs/tutorials/mariadb.md
Ping @serundeputy (or whoever).
> Fixed typo: 'given' to 'giving'

- docs/README.md
- [N/A] My code includes an update to the [CHANGELOG](https://github.com/lando/lando/tree/master/docs/changelog)
- [N/A] My code includes a [functional test](https://docs.devwithlando.io/dev/testing.html#functional-tests) if applicable
- [N/A] My code includes a [unit test](https://docs.devwithlando.io/dev/testing.html#unit-tests) if applicable
- [N/A] My code passes relevant CI status checks
> Fixed readme typo

- docs/config/security.md
> tiny documentation typo fix

- docs/tutorials/drupal7.md
> Fix typo in drupal7 tutorial.

- .platform.app.yaml
- docs/ads.txt
> Adding ads.txt.

- docs/started.md
> ISSUE #1707: Fixed typo `xdbeug` => `xdebug`

- docs/.vuepress/components/Lando.vue
- docs/.vuepress/config.js
- docs/README.md
- docs/package.json
- package.json
- website/.vuepress/components/Download.vue
- website/.vuepress/components/Footer.vue
- website/.vuepress/components/Lando.vue
- website/.vuepress/components/MadeByTandem.vue
- website/.vuepress/components/Memberships.vue
- website/.vuepress/components/Newsletter.vue
- website/.vuepress/config.js
- website/.vuepress/styles/index.styl
- website/README.md
- website/download/README.md
- website/memberships/README.md
- website/package.json
- yarn.lock
> 1410 website

- website/.vuepress/theme/components/Home.vue
- website/.vuepress/theme/layouts/Layout.vue
> Carbon seo4

- docs/README.md
- website/.vuepress/config.js
- website/.vuepress/theme/components/Home.vue
- website/.vuepress/theme/layouts/Join.vue
- website/.vuepress/theme/styles/index.styl
- website/alliance/join/README.md
- website/alliance/thanks/README.md
- website/download/README.md
> basic alliance signupz

- .github/FUNDING.yml
- docs/.vuepress/config.js
- docs/help/2019-changelog.md
- plugins/lando-services/services/memcached/builder.js
- plugins/lando-services/services/memcached/launch.sh
> Badcamp2020

- docs/help/2019-changelog.md
- plugins/lando-core/scripts/add-cert.sh
- plugins/lando-proxy/services/proxy/builder.js
- scripts/build-darwin.sh
- scripts/build-win32.ps1
> Update to Docker Desktop 2.1.0.3 for Catalina prep

- docs/guides/updating-to-rc2.md
- docs/help/2019-changelog.md
- examples/compose/README.md
- plugins/lando-recipes/types/laemp/builder.js
> Correct spelling with codespell

- lib/promise.js
- lib/shell.js
> Add VERY basic process management to shell.js

- lib/bootstrap.js
- lib/cli.js
- metrics/package.json
- metrics/plugins/bugsnag.js
- metrics/yarn.lock
- package.json
- yarn.lock
> Improve bugsnag reporting

- docs/guides/frontend.md
- [*] My code includes the latest code from the `master` branch
- [*] My code includes documentation updates if applicable.
> Fix node service link in frontend tooling guide.

- docs/basics/basics.md
@pirog Just a quick fix to the docs
> Fixing link to recipes page

- docs/config/solr.md
Fixed typo in Solr documentation.
> Fixed typo

- docs/guides/offline-dev.md
add extra breaks to fix ordered list
> formatting

- .travis.yml
- docs/.vuepress/components/GuideFooter.vue
- docs/.vuepress/components/GuideHeader.vue
- docs/.vuepress/components/YouTube.vue
- docs/guides/access-by-other-devices.md
- docs/guides/an-example-guide.md
- docs/guides/db-export.md
- docs/guides/db-import.md
- docs/guides/external-access.md
- docs/guides/frontend.md
- docs/guides/lando-info.md
- docs/guides/lando-phpstorm.md
- docs/guides/lando-with-vscode.md
- docs/guides/macos-pantheon-no-proxy.md
- docs/guides/offline-dev.md
- docs/guides/updating-to-rc2.md
- events/.vuepress/components/Newsletter.vue
- events/.vuepress/theme/components/Subscribe.vue
- examples/elasticsearch/README.md
- plugins/lando-alliance/tasks/guide-generate.js
- plugins/lando-alliance/templates/guide.template
> 0 alliance wrap3

- .travis.yml
- docs/contrib/evangelist-events.md
- docs/contrib/first.md
> #0: REvert version check

- blog/.vuepress/theme/components/CarbonAds.vue
- blog/posts/2020-02-10-q1-2020-update.md
- docs/.vuepress/components/NewsletterLearn.vue
- docs/.vuepress/theme/components/CarbonAds.vue
- docs/basics/first-app.md
- events/.vuepress/theme/components/Home.vue
- website/.vuepress/theme/components/CarbonAds.vue
- website/alliance/join/README.md
> #0: Update alliance announcement links

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/devops.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/guide.md
- .github/ISSUE_TEMPLATE/misc.md
- .github/ISSUE_TEMPLATE/security.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/stale.yml
- docs/help/2020-changelog.md
> Dev reboot aft

- api/data/sponsors.yml
> Updated sponsors through Feb 25th PST morning

- .circleci/config.yml
> #0: Add in wrapper workflow metadata to fix busted up CircleCI reporting

- api/data/contributors.yml
- lib/art.js
> Correct verb

- docs/config/postgres.md
> Fix typo; remove sentence fragment

- plugins/lando-services/scripts/sql-import.sh
Closes https://github.com/lando/lando/issues/2007
> Updated inline documentation for clarity.

- docs/config/env.md
> Add note about rebuilding to env vars config docs.

- docs/tutorials/mysql.md
> Add details for my.cnf overrides.

- docs/basics/installation.md
- docs/config/node.md
- docs/help/2020-changelog.md
- examples/node/.lando.yml
- examples/node/README.md
- plugins/lando-services/services/node/builder.js
> Pirog consolidated4

- plugins/lando-services/services/php/7.2-apache/Dockerfile
- plugins/lando-services/services/php/7.2-apache/README.md
- plugins/lando-services/services/php/7.2-fpm/Dockerfile
- plugins/lando-services/services/php/7.2-fpm/README.md
- plugins/lando-services/services/php/7.3-apache/Dockerfile
- plugins/lando-services/services/php/7.3-apache/README.md
- plugins/lando-services/services/php/7.3-fpm/Dockerfile
- plugins/lando-services/services/php/7.3-fpm/README.md
> updated xdebug in php 7.2, 7.3 containers to use latest

- docs/config/node.md
- docs/help/2019-changelog.md
- plugins/lando-services/services/node/builder.js
Added Node.js 12 to the node service supported array.
> lando#1866 Add Node.js 12 LTS to supported versions

- api/package.json
- api/routes/sponsors.js
- api/server.js
- api/yarn.lock
- package.json
- yarn.lock
> Automate sponsor4

- docs/.vuepress/guides.json
- docs/guides/overriding-a-service-version.md
> Add a guide on overriding services

- plugins/lando-services/services/mariadb/builder.js
Fix a typo in the image tag and also update to the latest release.
> Fix mariadb 10.4 image tag

- docs/guides/access-by-other-devices.md
Step two gets lost under the Linux heading. Added more headings to clarify.
> Make steps clearer.

- docs/help/2020-changelog.md
- examples/services/README.md
- lib/compose.js
> Update changelog and kick off func testing

- docs/config/phpmyadmin.md
> Update phpmyadmin docs - removed unsupported versions

- docs/config/env.md
> Fix typo in 'env.md'

- api/data/contributors.yml
> Add uberhacker to the team

- .circleci/config.yml
- api/lib/slack.js
- api/routes/subscribe.js
- blog/posts/2020-02-18-amazee.io-lando-sponsorship.md
- docs/contrib/admin-sponsors.md
- docs/guides/how-to-wire-up-browsersync-and-gulp-in-my-lando-app.md
- docs/help/2020-changelog.md
- examples/lagoon-drupal/README.md
- lib/art.js
- lib/router.js
- lib/shell.js
- lib/utils.js
- plugins/lando-core/app.js
- plugins/lando-pantheon/scripts/pull.sh
- plugins/lando-pantheon/scripts/push.sh
- plugins/lando-proxy/lib/utils.js
- plugins/lando-services/app.js
> Codespell and grammar changes

- docs/config/laravel.md
> Fix laravel.md docs file headers.

- api/data/contributors.yml
Hello :wave:, I followed the docs on first time contributions and unlocked the secret-toggle leading me to this PR.
> Add Christopher Martin as a contributor

- docs/basics/basics.md
- docs/basics/config.md
- docs/basics/init.md
- docs/basics/poweroff.md
- docs/basics/rebuild.md
- docs/basics/share.md
- docs/basics/ssh.md
- docs/help/2020-changelog.md
> Spell check docs/basics

- docs/basics/installation.md
- docs/help/2020-changelog.md
- installer/darwin/mpkg/Distribution
- installer/darwin/mpkg/Resources/en.lproj/Localizable.strings
- lib/shell.js
- plugins/lando-proxy/services/proxy/builder.js
> Pirog rrc7

- config.yml
- docs/.vuepress/guides.json
- docs/guides/installing-node-in-your-lando-php-service.md
- docs/guides/installing-php-extensions-on-lando.md
- docs/help/2020-changelog.md
- examples/php-extensions/.gitignore
- examples/php-extensions/.lando.yml
- examples/php-extensions/Dockerfile.custom
- examples/php-extensions/README.md
- examples/php-extensions/index.php
- examples/php/.lando.yml
- examples/php/Dockerfile.node
- examples/php/README.md
- installer/darwin/mpkg/docker.pkg/Scripts/postinstall
- installer/win32/engine.ps1
- scripts/build-darwin.sh
- scripts/build-linux.sh
- scripts/build-win32.ps1
> 3.0.x 2dd plus guides

- docs/.vuepress/components/Newsletter.vue
- docs/.vuepress/guides.json
- docs/config/pantheon.md
- docs/guides/using-compass-on-a-lando-node-service.md
- docs/help/2020-changelog.md
- examples/node12/.lando.yml
- examples/node12/README.md
- examples/node12/package.json
- examples/node12/yarn.lock
- lib/app.js
> 3.0.x 2 more guides

- docs/config/drupal9.md
> Update lando init command for Drupal 9 RC1

- docs/guides/installing-node-in-your-lando-php-service.md
This simply updates the Emulsify link to the more recent package. Thank you for mentioning us!
* [Writing Lando …
> Updating to new Emulsify package

- docs/config/security.md
These are the commands I had to use to get it working. Taken from here. https://bbs.archlinux.org/viewtopic.php?id=235724
> [docs] added arch linux commands to trust the lando ca

- plugins/lando-recipes/recipes/backdrop/builder.js
Adding `drush backdrop-subtheme-basis`
Adding `drush ws`
> Adding backdrop-drush-extension 1.4.0 as default.

- plugins/lando-proxy/lib/warnings.js
> #2294: Fix the link to proxy documentation

- docs/basics/init.md
- docs/config/drupal7.md
- docs/config/drupal8.md
- docs/config/drupal9.md
- examples/drupal7/README.md
- examples/drupal8/README.md
- examples/drupal9/README.md
- website/README.md
Resolves #2249
This should be merged in when Drupal 9.0.0 is tagged later today.
> Update Drupal Download URLs

- api/data/contributors.yml
- docs/config/pantheon.md
- docs/help/2020-changelog.md
- examples/pantheon-wordpressnetworkdomain/.gitignore
- examples/pantheon-wordpressnetworkdomain/README.md
- examples/pantheon-wordpressnetworkdomain/remove-keys.sh
- examples/pantheon-wordpressnetworkfolder/.gitignore
- examples/pantheon-wordpressnetworkfolder/README.md
- examples/pantheon-wordpressnetworkfolder/remove-keys.sh
- plugins/lando-pantheon/lib/utils.js
- plugins/lando-pantheon/recipes/pantheon/wordpress.conf.tpl
- plugins/lando-pantheon/recipes/pantheon/wordpress_network.conf.tpl
- plugins/lando-pantheon/scripts/pull.sh
> 1425 pantheon site networks

- docs/config/platformsh.md
- experimental/plugins/lando-platformsh/app.js
- experimental/plugins/lando-platformsh/index.js
- experimental/plugins/lando-platformsh/lib/auth.js
- experimental/plugins/lando-platformsh/lib/pull.js
- experimental/plugins/lando-platformsh/lib/tooling.js
- experimental/plugins/lando-platformsh/recipes/platformsh/builder.js
- experimental/plugins/lando-platformsh/scripts/psh-pull.sh
- lib/logger.js
@mikemilano i wouldnt worry about manually testing this right now, ill be adding it into the functional D8 tests once i get those rolling. 
Def could use "no red flags" level of code review though.
> 2309 psh better pull

- docs/basics/config.md
- docs/basics/ssh.md
- docs/config/php.md
- docs/guides/frontend.md
- docs/help/2020-changelog.md
- examples/drupal7/README.md
- examples/pantheon-drupal7/README.md
- examples/pantheon-drupal8/README.md
- examples/pantheon-wordpress/README.md
- examples/pantheon-wordpressnetworkdomain/README.md
- examples/pantheon-wordpressnetworkfolder/README.md
- lib/art.js
- plugins/lando-core/scripts/user-perm-helpers.sh
- plugins/lando-services/scripts/sql-import.sh
- plugins/lando-services/services/php/builder.js
- plugins/lando-tooling/index.js
- plugins/lando-tooling/lib/utils.js
> #1918: Fix bug causing piping in docker execd tooling to silently fail

- experimental/plugins/lando-platformsh/README.md
Added the python source code directories to the README
> Added Python source links

- experimental/plugins/lando-platformsh/app.js
- experimental/plugins/lando-platformsh/lib/warnings.js
Added warning for unsupported services.
> #2317 Added warning for unsupported services.

- docs/help/2020-changelog.md
- examples/drupal8/.lando.local.yml
- plugins/lando-recipes/types/drupaly/builder.js
> #2372: Fix bug with non-semantic drush versions throwing errors

- blog/posts/2020-03-20-5-things-to-do-after-you-install-lando.md
- docs/help/dns-rebind.md
> 2349   inclusive language

- experimental/plugins/lando-platformsh/lib/config.js
- experimental/plugins/lando-platformsh/lib/run.js
- experimental/plugins/lando-platformsh/lib/utils.js
- experimental/plugins/lando-platformsh/lib/yaml.js
> 2416 yaml tagz

- docs/config/services.md
- docs/help/2020-changelog.md
- examples/drupal8/README.md
- lib/utils.js
- plugins/lando-recipes/recipes/drupal8/builder.js
- plugins/lando-recipes/services/init/builder.js
- plugins/lando-sharing/lib/utils.js
- plugins/lando-sharing/services/mounter/builder.js
> Mutagen prep

- docs/config/drupal9.md
> Remove Drush 8 specific examples from Drupal 9 recipe docs.

- docs/config/platformsh.md
- docs/config/recipes.md
- examples/platformsh-drupal8/README.md
- experimental/plugins/lando-platformsh/lib/tooling.js
- experimental/plugins/lando-platformsh/scripts/psh-exec.sh
- lib/bootstrap.js
> Platform2443 2401

- docs/help/2020-changelog.md
- plugins/lando-tooling/lib/utils.js
> P pull push

- docs/config/platformsh.md
- docs/help/2020-changelog.md
> Fix invalid url in platformsh.md

- examples/platformsh-kitchensink/README.md
- integrations/lando-platformsh/lib/services.js
- integrations/lando-platformsh/services/platformsh-chrome-headless/builder.js
This PR includes headless chrome service and tests.
> Enabled the chrome-headless service.

- integrations/lando-pantheon/scripts/pantheon.sh
Pretty easy peezy, just add another symlink
> Issue #2421: Symlink the /code dir to mirror COE directories

- docs/help/2020-changelog.md
- lib/utils.js
- plugins/lando-tooling/lib/utils.js
> #2492: Improve tooling command parsing

- docs/config/platformsh.md
- docs/config/proxy.md
- docs/help/2020-changelog.md
- examples/proxy/.lando.yml
- examples/proxy/README.md
- examples/proxy/web/index.php
- integrations/lando-platformsh/app.js
- integrations/lando-platformsh/lib/config.js
- integrations/lando-platformsh/lib/proxy.js
- integrations/lando-platformsh/services/platformsh-php/builder.js
- plugins/lando-networking/app.js
- plugins/lando-proxy/lib/utils.js
> #2507: Provide configuration options to traefiks middleware layer

- .circleci/lando.yml
- config.yml
- docs/help/2020-changelog.md
- installer/darwin/mpkg/docker.pkg/Scripts/postinstall
- plugins/lando-proxy/index.js
- scripts/build-darwin.sh
- scripts/build-linux.sh
- scripts/build-win32.ps1
> 2531 docker up

- plugins/lando-core/types/utility/Dockerfile
- plugins/lando-core/types/utility/README.md
> Pirog patch 1

- docs/config/platformsh.md
- docs/help/2020-changelog.md
- examples/platformsh-drupal8/README.md
- integrations/lando-platformsh/app.js
- integrations/lando-platformsh/lib/pull.js
- integrations/lando-platformsh/lib/push.js
- integrations/lando-platformsh/recipes/platformsh/init.js
- integrations/lando-platformsh/scripts/psh-clone.sh
- package.json
- plugins/lando-core/types/utility/Dockerfile
- plugins/lando-core/types/utility/README.md
- yarn.lock
> Platform pirog5

- api/data/contributors.yml
- docs/config/platformsh.md
> Platform.sh documentation edits + adds me as contrib

- docs/help/2020-changelog.md
- lib/daemon.js
> #2351: Improve linux docker autostart logic and error message

- integrations/lando-pantheon/lib/utils.js
> Duplicate settings and conf in getPantheonSettings so things like 'file_private_path' get written to settings instead of wiped out.

- docs/config/platformsh.md
- docs/help/2020-changelog.md
- examples/pantheon-drupal8/README.md
- examples/platformsh-drupal8/README.md
- examples/platformsh-kitchensink/README.md
- integrations/lando-platformsh/app.js
- integrations/lando-platformsh/lib/config.js
- integrations/lando-platformsh/lib/yaml.js
- integrations/lando-platformsh/services/platformsh-php/builder.js
- integrations/lando-platformsh/services/platformsh-varnish/builder.js
> 2445 psh includes

- docs/config/platformsh.md
- docs/help/2020-changelog.md
- integrations/lando-platformsh/app.js
- integrations/lando-platformsh/lib/config.js
- integrations/lando-platformsh/lib/pull.js
- integrations/lando-platformsh/lib/push.js
- integrations/lando-platformsh/scripts/psh-pull.sh
- integrations/lando-platformsh/scripts/psh-push.sh
> Platform pass9

- docs/basics/basics.md
> Fix link in docs

- docs/basics/basics.md
- docs/config/lagoon.md
- docs/config/pantheon.md
- docs/config/services.md
- docs/config/tooling.md
- docs/guides/frontend.md
- docs/guides/updating-to-rc2.md
Easy navigation and easy reading
> Fix broken url in the docs

- docs/config/platformsh.md
- docs/help/2020-changelog.md
- examples/lagoon-drupal9-advanced/README.md
- examples/lagoon-drupal9-postgres/README.md
- integrations/lando-platformsh/recipes/platformsh/builder.js
- integrations/lando-platformsh/scripts/psh-build.sh
> Platforms pass10

- docs/help/2020-changelog.md
- examples/badname/.lando.yml
- lib/utils.js
- package.json
- yarn.lock
> Fixed bug causing some special characters in app names to crash app

- .circleci/lando.yml
- config.yml
- docs/help/2020-changelog.md
- scripts/build-darwin.sh
- scripts/build-win32.ps1
> Update to Docker Desktop 2.5.0.0

- docs/basics/README.md
There may be other places to reference, but this is the one I found so far.
> Include Platform.sh support

- .circleci/lando.yml
- config.yml
- contributors.yml
- docs/basics/README.md
- docs/config/lagoon.md
- docs/config/pantheon.md
- docs/config/platformsh.md
- docs/guides/installing-php-extensions-on-lando.md
- docs/help/2020-changelog.md
- examples/drupal9/README.md
- examples/php-extensions/.lando.yml
- examples/php-extensions/Dockerfile.custom
- examples/platformsh-drupal8/README.md
- integrations/lando-platformsh/app.js
- plugins/lando-recipes/recipes/drupal9/builder.js
- scripts/build-darwin.sh
- scripts/build-win32.ps1
> Pirog03021

- docs/.vuepress/config.js
- docs/.vuepress/theme/components/Footer.vue
- docs/config/recipes.md
Added Symfony recipe references in docs.
> Symfony recipe references into docs.

- bin/lando.dev
- contributors.yml
- docs/config/php.md
- docs/help/2020-changelog.md
- examples/php/.lando.yml
- examples/php/README.md
- plugins/lando-services/scripts/install-composer.sh
> Pirog03023

- docs/config/platformsh.md
Add the var override to the docs …
> Update docs for XDebug on p.sh

- .circleci/lando.yml
- config.yml
- docs/help/2020-changelog.md
- examples/php/README.md
- installer/darwin/mpkg/docker.pkg/Scripts/postinstall
- plugins/lando-core/scripts/user-perm-helpers.sh
- scripts/build-darwin.sh
- scripts/build-win32.ps1
> Update to Docker Desktop 3.0.1

- docs/config/node.md
My screen reader says "Thank you for the challenge". …
> Typo: dependenices -> dependencies

- docs/basics/installation.md
@dustinleblanc/@pirog you good with this?
> Add mention of M1 mac support

- docs/basics/installation.md
> update: brew command changed as current method will fail

- docs/basics/updating.md
v3.0.0 version links are 2+ years old and no longer relevant
* [Writing Lando …
> remove old version links from Updating section

- .circleci/config.yml
- docs/config/lagoon.md
- docs/help/2020-changelog.md
- integrations/lando-lagoon/app.js
- integrations/lando-lagoon/lib/config.js
- integrations/lando-lagoon/lib/services.js
- integrations/lando-lagoon/scripts/lagoon-pull.sh
- integrations/lando-lagoon/services/lagoon-none/builder.js
- integrations/lando-platformsh/app.js
- plugins/lando-core/compose/lando/builder.js
> Pirog03025b

- docs/.vuepress/theme/components/LayoutSponsors.vue
Sponsor links in right sidebar broken/js errors.
> Fixing sponsors links.

- docs/.vuepress/config.js
- docs/contrib/evangelist-present.md
- docs/contrib/sponsor-faq.md
- docs/contrib/sponsor-upsell.md
- docs/contrib/talking-points.md
Updating the docs to fix some dead links; refactored their old target page to focus on convincing other people/orgs to sponsor Lando.
> Add instructions on how to convince others to sponsor Lando.

- docs/.vuepress/config.js
- docs/help/2020-changelog.md
- docs/help/2021-changelog.md
> move changelog to 2021

- integrations/lando-pantheon/scripts/pantheon.sh
> #2859: Allow access to pantheon binding.pem from new location

- bin/lando.js
- core/art.js
- core/formatters.js
- docs/help/2021-changelog.md
- integrations/lando-platformsh/scripts/psh-exec.sh
- lib/config.js
> #2688: Force DOCKER_BUILDKIT=1 for now

- docs/config/acquia.md
> Update acquia.md docs.

- docs/config/acquia.md
> correcting `experimental`

- docs/config/laravel.md
the public directory is outside the `app/` directory. …
> Adding a minor update to laravel docs. 

- docs/config/platformsh.md
> Fix typo on p.sh xdebug doc

- plugins/lando-core/scripts/lando-entrypoint.sh
First PR, just a tiny typo fix. @pirog @amyh @DustinLeblanc
> Typo anotehr -> another

- docs/config/elasticsearch.md
- plugins/lando-services/services/elasticsearch/builder.js
> Unlock elasticsearch 7.10.x-7.12.x

- docs/config/drupal8.md
> Replace reference to backdrop recipe with drupal8

- experimental/lando-acquia/recipes/acquia/init.js
Copy fixed as suggested by Acquia
> Updated Acquia token dialog

- docs/config/security.md
- [X ] My code includes documentation updates if applicable.
> Update docs to make Firefox security instructions clearer

- contributors.yml
👋 Adding myself to contributors.yml per your [docs](https://docs.lando.dev/contrib/first.html#recommended-workflow).
> Adding sarahg to the team.

- docs/config/postgres.md
- plugins/lando-services/services/postgres/builder.js
Hi, this adds support for Postgres 13 and is based on #2133
> Add support for Postgres 13

- docs/config/nginx.md
> Fix broken default nginx config link

- docs/config/php.md
> Fix broken default PHP config link

- docs/.vuepress/config.js
> Update the branch for edit links

- docs/config/laravel.md
> Resolves #3053

- docs/config/lagoon.md
I think we can use kinder language here - plus, not everyone who reads this will be a developer.
* [Writing Lando …
> More inclusive language in Lagoon docs

- docs/basics/installation.md
> Update 'From source' section in installation.md

- docs/config/laravel.md
> Fix link to Laravel recipe

- docs/contrib/first.md
Updates docs to reflect change from `master` branch to `main`
* [Writing Lando …
> Updates `master` to `main`

- docs/.vuepress/theme/components/Footer.vue
> Update Footer Links

- docs/config/acquia.md
Removed Drupal version numbers and WordPress
> clarified the description

- docs/config/postgres.md
- docs/config/recipes.md
- docs/config/symfony.md
- docs/config/wordpress.md
- docs/help/2021-changelog.md
Corresponding lando-cli pr:
https://github.com/lando/cli/pull/68
> Add support for postgres 14

- installer/macos/mpkg/Resources/en.lproj/Localizable.strings
> Issue #3530: Minor spelling mistake

- .github/ISSUE_TEMPLATE/core-next.md
- .github/ISSUE_TEMPLATE/core.md
Fixes typos referenced in #3708
> Issue template typo fix
