- docs/tutorials/backdrop.md
Views is part of Backdrop core so using `webform` as the example.
> Update lando drush dl example.

- docs/tutorials/setup-additional-tooling.md
Based on discussion last week in slack, this adds an example to the docs for using events to create tooling that runs on multiple services. I added it to the Tooling tutorial because I don't think I would have found it if it was under events.
> Add tooling + events example to the docs

- docs/tutorials/macos-pantheon-no-proxy.md
This tutorial may be helpful for users (like me) who happen to have port 80 in use and are running into issues with the proxy container not resolving properly.
> Add tutorial on how to set up a Pantheon app without a proxy in macOS

- docs/tutorials/frontend.md
Fixed a little mistake in the documentation, in the tooling section the service for npm says npm, while it should be node
- [x ] My code includes documentation updates if relevant.
> Change npm service to node

- docs/tutorials/composer-tutorial.md
This is just a tiny update on the documentation.
> Typo in composer-tutorial documentation.

- docs/SUMMARY.md
- docs/config/proxy.md
- docs/tutorials/access-by-other-devices.md
@pirog @serundeputy Here's an addition to the docs to address connecting to lando via devices on a local network; this was requested in the kalabox issue queue: https://github.com/kalabox/kalabox/issues/1807
I just set this up for myself today so I thought I would share my notes.
> proxy docs: add info on connecting from other devices on local network

- docs/config/config.md
I changed the example from `echo "proxy: 'OFF'" > ~/.lando/config.yml` to `echo "proxy: 'OFF'" >> ~/.lando/config.yml` so that users wont blow away their entire config if they have one with just the proxy setting.
Now it should append that option to the current config if one is there instead of overwriting it.
> Added extra ">" in example of updating the ~/.lando/config.yml

- docs/installation/installing.md
I was going to try out Lando and noticed no mention of the fantastic http://get.docker.com site.
The main "Install Docker" documentation is a bit... verbose. I use the get.docker.com script, which "Just Works" on most Linux distros.
Looking forward to testing this out!
====
> Add link to get.docker.com for "quick & easy install" of docker on Linux

- docs/tutorials/frontend.md
There is an indentation typo. The `build` method needs to be indented under `services:node` instead of being at the same level as `node`.
> Fix indentation with services:node:build

- docs/tutorials/drupal6.md
The Accessing services (eg your database) from the host is currently pointing to http://docs.devwithlando.io/tutorials/frontend.html instead of https://docs.devwithlando.io/tutorials/access-by-other-devices.html
> Fix Drupal 6 Accessing services link

- lib/cli.js
- package.json
This PR disallows running Lando from the CLI with `sudo` or with elevated privileges on Windows.
Running `sudo lando list` should cause an error message to be thrown and the process to exit. This doesn't work with just plain old `sudo lando` because of the `demandCommand()` call in cli.js. I've made a few attempts to override that and perhaps make use of yargs' `check` function, but I wasn't able to get that to work. We should consider adding more verbose output to give users more info on why this is bad, why they may be trying to do it, and how to fix that, perhaps just a link to docs.
> Closes #545

- lib/metrics.js
- plugins/lando-core/lib/tasks/share.js
@pirog I was able to add the metrics call to `reportAction()` to `share.js` where the `app` object was/is available.
> thinktandem/horoscope#197: Adding metrics for lando share command.

- docs/dev/testing.md
The documentation to run bats tests is wrong, fix attached.
> Fix bats test command documentation

- plugins/lando-recipes/recipes/drupal7/drupal7.js
Didn't go through any of the above because I don't know what I'm doing (I really don't) and couldn't find the Drush Launcher version anywhere else in files so even though there's `drupal7` in the filename it seems it's there we should update the launcher version. Please just iterate over this PR where it's required.
This PR is for #666
> Update Drush Launcher to 0.5.1

- plugins/lando-core/lib/tasks/destroy.js
I don't think this code change actually works; just hoping to spark conversation about the merits of averting destruction by default (currently, pressing `<enter>` results in total descruction).
> Make aversion of destruction the default action

- docs/started.md
Fix a typo in docs `started.md` file, **_LEMP_** stack was written **_LENO_** stack.
> Fix docs typo started.md

- examples/lamp2/.lando.yml
Just a small change to docs; no code changes.
This is already in the `lamp` example, but this is the example recipe that shows up on /tutorials/lamp.html, where I went looking for it.
> Document lamp appserver `via` option on recipe tut

- bin/lando.js
- docs/changelog/2018.md
- docs/config/config.md
- lib/config.js
- plugins/lando-engine/lib/env.js
- test/config.spec.js
- yarn.lock
This should allow folks to use Lando in environments like CircleCI where the Docker daemon is running on a remote server. The injected env var needs to be a JSON string for this to work. I can add docs too before we merge. @pirog thoughts on this? I wanted to add a test to this too, but pending the merge of some other test code, I didn't want to muck with duplicating stuff.
> Closes #647 - Allow Remote Docker

- .github/PULL_REQUEST_TEMPLATE.md
- docs/config/build.md
- docs/dev/services.md
Some links to Advanced Service Configuration in the docs are broken. For example, see:
- https://docs.devwithlando.io/config/build.html
- https://docs.devwithlando.io/dev/services.html
----
- ~[ ] My code passes relevant CI status checks~ N/A
- ~[ ] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))~ N/A
- ~[ ] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))~ N/A
> [docs] Fix links to Advanced Service Configuration and Committers

- examples/laravel/.lando.yml
Ran into this while testing examples for next release, this needs to be bumped to accomodate the `laravel new` command
> Latest Laravel needs 7.1

- docs/tutorials/lando-and-ci.md
- examples/lando-and-ci/.travis.yml
Just updating the documented latest dev download URL.
> Fix download URL in CI docs

- examples/mysql/.lando.yml
This fixes a very minor typo in the mysql `.lando.yml` file: `avialable` -> `available`.
> Fix typo in mysql lando example file

- docs/config/env.md
In the existing wording, it sounds like you could drop any `.env` file into your app root to have it parsed. In reality, the file must be named exactly `.env`. By comparison, if I were to say you could drop a `.yml` file into your app to have it parsed, you probably wouldn't think to name the file `.yml` but rather that any .yml would be parsed.
> Be more specific about .env file name

- docs/SUMMARY.md
- docs/services/php.md
- docs/tutorials/lando-with-vscode.md
I have added a new page under tutorials to explain how to get XDebug working with Lando in VS Code. 
I would like to update the CHANGELOG but I was not sure how to edit this file actually.
> #626 - Add tutorial for XDebug in VS Code

- docs/services/php.md
While attempting to setup XDEBUG I noticed on the php page under the using-xdebug section there is a broken link to the vscode tutorial:
https://docs.devwithlando.io/services/php.html#using-xdebug
This PR changes the link to the proper URL:
https://docs.devwithlando.io/tutorials/lando-with-vscode.html
> Fix broken link on the php documentation page (xdebug section)

- docs/services/php.md
- docs/tutorials/setup-additional-tooling.md
- [NA] My code passes relevant CI status checks
- [NA] My code includes a test if applicable ([see here](https://docs.devwithlando.io/dev/testing.html))
- [NA] My code includes an update to the `CHANGELOG` ([see here](https://github.com/kalabox/lando/tree/master/docs/changelog))
- [NA] My code includes documentation updates if relevant.
- [NA] I have pinged [a project committer](https://docs.devwithlando.io/contrib/contributing.html#committers) when I think my code is ready for prime time.
If you are unclear about …
>  Docs: `run_as_root`, removal of extras:

- examples/laravel/.lando.yml
Updated capitalization
Updated Laravel links to use newer 5.6 documentation
fixed copy/pasta `drupal` -> `Laravel`
> Laravel Docs: tweaks, use 5.6 doc links

- docs/tutorials/offline-dev.md
Updated docs to use *.test for local development instead of *.localhost, due to issues on Mojave. Also removes reference to *.local in docs. (Follow-up for #880)
c.f. https://github.com/laravel/homestead/issues/695
> Update offline tutorial for Mac OS Mojave compatibility

- docs/config/tooling.md
The drush command example
```
cmd:
- "drush"
- "--root=/app/web"
```
actually runs two commands: `drush` and `--root=/app/web`, which isn't a command. This changes the drush example to match other examples like "`cmd: composer --ansi`".
If you are unclear about any of the above please add comments below so we can improve our process.
> Update example drush command

- examples/dockerfile/README.md
If we don't stop containers first, the images don't get removed, only untagged and show as none:none.
If you are unclear about any of the above please add comments below so we can improve our process.
> Add `lando stop` step to dockerfile example "burn to ground" section

- plugins/lando-recipes/recipes/pantheon/mysql/my.cnf
This PR relates to #1058 which was closed without a corresponding code change because the submitter resolved his issue locally to his own satisfaction.
Pantheon's MariaDB is configured to support multibyte utf8mb4 via the configuration `innodb_large_prefix=true`. Databases on Pantheon using utf8mb4 may fail to import during `lando pull` or `lando db-import` as a result of this configuration mismatch.
This PR alters the my.cnf file provided by the pantheon recipe to support utf8mb4 by setting `innodb_large_prefix=true` as above, as well as the related `innodb_file_format=barracuda` as required per https://mariadb.com/kb/en/library/innodb-system-variables/#innodb_large_prefix
Default character set or collation are not altered, so existing working configurations should be unaffected.
When …
> Pantheon recipe my.cnf to match pantheon.io config for utf8mb4 support

- examples/wordpress/.lando.yml
This is just a very minor verbiage correction I noticed while browsing the docs. None of the checkboxes are really relevant here.
> Fix reference to Drupal in WordPress example

- docs/tutorials/lando-info.md
Correct spelling of "application" and add missing verb.
It's just a typo in the documentation, so there are no corresponding functional tests, unit tests, or status checks, and no CHANGELOG entry.
If you are unclear about any of the above please add comments below so we can improve our process.
> Correct typos in lando-info.md

- docs/guides/updating-to-rc2.md
Running `lando php -e "phpinfo();"` results in `Could not open input file: phpinfo();`. Adjusting to `lando php -r "phpinfo();"` prints expected php info results.
> Update -e to -r on the sample command in rc2 upgrade guide

- docs/guides/updating-to-rc2.md
Example documentation incorrectly lists `service` instead of `services`.
> Minor documentation fix for upgrades to RC2.

- docs/guides/updating-to-rc2.md
Link to Drush info for Drupal8 has typo.
> drupal8 link typo

- docs/guides/lando-with-vscode.md
We need to update example in documentation to reflect new configuration in `.lando.yml` files. 
This PR update the guide about VSCode and Xdebug to show users how they should structure their `.lando.yml` file for Lando rc1 and Lando rc2+.
> Update VSCode example to work with rc2+

- docs/guides/lando-with-vscode.md
Fix an inconsistency in the example config.
"Normal" is not a valid config, replaced with right config name.
> Compound configuration names need to match

- docs/config/proxy.md
> typo "*.lando.site" --> "*.lndo.site"

- installer/linux/scripts/postinst
Fixes #1586 - checks whether max_map_count exists before attempting to bump it, fixing installation on platforms without max_map_count, including WSL.
> #1586: ONLY ATTEMPT TO BUMP MAX_MAP_COUNT IF MAX_MAP_COUNT EXISTS

- docs/tutorials/compose.md
tweaked improper plural and double "service" since the context should be clear from the first reference.
> grammar fixes

- docs/tutorials/php.md
Page: https://docs.devwithlando.io/tutorials/php.html#toggling-xdebug
Issue: Under section VSCODE, link _Setup XDebug in Visual Studio Code Guide_ links to https://docs.devwithlando.io/tutorials/guides/lando-with-vscode.md but should be 
https://docs.devwithlando.io/guides/lando-with-vscode.md
> DOCS: Fix link for "Setup XDebug in Visual Studio Code Guide"

- docs/tutorials/drupal7.md
I didn't change anything in the meaning, just the presentation.
> Documentation: improved spelling and punctuation

- docs/tutorials/drupal8.md
Minor documentation updates only, no code changes.
> Fixes some spelling/grammar in the Drupal 8 docs

- docs/installation/system-requirements.md
Just a tiny URL fix to the make the link to the Hyper-V docs work. There was an `l` left off the end. 🙂
> Fix docs link to Windows Hyper-V documentation

- docs/config/tomcat.md
https://tomcat.apache.org is the correct link; https://tomcat.tomcat.org appears to be a spam site promising 'rewards'
> fix link to tomcat site & remove spam link

- plugins/lando-core/scripts/add-cert.sh
Lando generated certs after 1st July 2019 are not accepted at all even after trusting the CA on iOS 13 and macOS 10.15+ (giving ERR_CERT_REVOKED in the browser) 
See: https://support.apple.com/en-us/HT210176
This PR restores the cert-generation into compatibility by:
* Adding serverAuth to the extended key usage
* Limiting validity to 825 days.
> cert-validity-fix: Fix cert validity on iOS 13+ and macOS 10.15+

- docs/config/tooling.md
> Fix YAML error in tooling docs

- docs/contrib/contributing.md
Should link to https://docs.lando.dev/contrib/started.html not https://docs.lando.dev/dev/started.html
FYI the ZenHub board link on that page doesn't seem to point anywhere
> Broken link to code contribution in docs

- docs/contrib/sponsor-benefits.md
- website/.vuepress/theme/components/SponsorshipTiers.vue
- website/.vuepress/theme/components/Tier.vue
- website/.vuepress/theme/layouts/Sponsor.vue
Removes the preview=true on the sponsorship links for github
> Remove preview=true from GH sponsor links

- docs/guides/lando-phpstorm.md
The text mentions a video tutorial, but the video link was removed in commit 1efa15e998bbc96cc4fc25f56227b756b5ff7d1b
> Restore video in Lando PHPStorm guide

- lib/art.js
This pull request changes the language that lando displays when running `lando restart`. 
The current language:
`Stopping your app... just so we can start it up again ¯\_(ツ)_/¯`
I'm probably sensitive, but this language makes me feel like lando is poking fun at me for choosing `restart`, and that I should have chosen a better course of action. I changed it to the following, but am open to whatever:
`Stopping and restarting your app...Shiny!`
> Be nicer to sensitive folks like @q0rban: remove smirk from lando restart

- docs/config/drupal8.md
The old method of adding a `$base_url` does not work. …
> Update proper way to add a local Drush uri setting

- docs/config/php.md
- docs/help/2019-changelog.md
- examples/php/.lando.yml
- examples/php/README.md
- plugins/lando-services/services/php/7.4-apache/Dockerfile
- plugins/lando-services/services/php/7.4-apache/README.md
- plugins/lando-services/services/php/7.4-fpm/Dockerfile
- plugins/lando-services/services/php/7.4-fpm/README.md
- plugins/lando-services/services/php/builder.js
This adds PHP 7.4 support to Lando. It follows similar setup as the previous versions and includes the same extensions as 7.3
> #1891: php 7.4 support

- docs/basics/basics.md
- docs/config/recipes.md
- docs/config/services.md
- docs/config/tooling.md
Just fixing some broken links in the docs. :)
> fix contrib-plugins.md links

- docs/config/ssh.md
Without the -s the lando ssh command for the appserver config edit won't work. …
> Missing -s in line 35

- docs/contrib/evangelist-intro.md
This is just a minor documentation update to fix two bad twitter URLs.
> Fix bad twitter URLs (should be .com, not .org)

- docs/config/mailhog.md
Small typo in `mailhog.md` (`his` -> `is`).
> Fix typo in mailhog.md

- docs/config/recipes.md
The current link to creating your own recipe is out of date and 404s.
* …
> Fix create recipe link

- plugins/lando-proxy/lib/utils.js
parsedUrl.pathname is '/' if there is no subdir, but that should not be sent as a stripped prefix.
Fixes #2149
> Only add PathPrefixStrip if we actually have a subdir.

- experimental/plugins/lando-platformsh/scripts/psh-boot.sh
@mikemilano this should be ready to test.
We should try to merge it as soon as we can since it will reduce a lot of dev overhead.
> #2320: Wait until mock socket is ready before p.sh boot/start

- docs/basics/installation.md
Address unmet dependencies error when `sudo apt upgrade` is ran.
https://serverfault.com/a/506993
https://superuser.com/a/815371
> Add troubleshooting instructions for unconventional deb installs.

- experimental/plugins/lando-platformsh/scripts/psh-fake-rpc.py
This PR removes `close() ` in `psh-fake-rpc.py` to resolve errors in container logs.
> #2364 Removed close to resolve the RPC errors in container logs.

- experimental/plugins/lando-platformsh/services/platformsh-elasticsearch/builder.js
- experimental/plugins/lando-platformsh/services/platformsh-mariadb/builder.js
- experimental/plugins/lando-platformsh/services/platformsh-memcached/builder.js
- experimental/plugins/lando-platformsh/services/platformsh-mongodb/builder.js
- experimental/plugins/lando-platformsh/services/platformsh-php/builder.js
- experimental/plugins/lando-platformsh/services/platformsh-postgresql/builder.js
- experimental/plugins/lando-platformsh/services/platformsh-redis/builder.js
- experimental/plugins/lando-platformsh/services/platformsh-solr/builder.js
- plugins/lando-core/compose/lando/builder.js
This PR adds support for the `supportedIgnore` service config which bypasses the version validation against the `supported` array.
> #2395 Added supportedIgnore config to bypass supported version check

- docs/contrib/allianceroles.md
- docs/contrib/contrib-intro.md
While browsing the docs, I noticed that a few links are broken. Let's get them working and get more allies! :)
> Fixes documentation links in the Alliance section

- docs/config/security.md
The suggested Debian steps, as well as the "warning Firefox" steps don't seem to work for the Ubuntu + Firefox combination. Issue discussed in #2047.
> Adds Ubuntu Firefox specific steps to Trusting the CA documentation

- docs/help/2020-changelog.md
- integrations/lando-platformsh/app.js
- integrations/lando-platformsh/lib/config.js
- integrations/lando-platformsh/lib/run.js
- integrations/lando-platformsh/lib/utils.js
- integrations/lando-platformsh/scripts/psh-build.sh
- integrations/lando-platformsh/types/platformsh-appserver/builder.js
- plugins/lando-proxy/lib/utils.js
@mikemilano the check for this ended up being a lot easier than we had originally thought. We didnt need to check for the entrypoint just whether the webroot existed or not.
> #2529: Use destination parameter if needed when doing platform build

- docs/help/2020-changelog.md
- examples/pantheon-drupal8/README.md
- integrations/lando-pantheon/lib/utils.js
I had some weird issues with running Drush on Drupal 8 with the default Pantheon settings.php files, but I managed to get it working and can confirm this works:
> Issue #2504: Skip permissions hardening by default on Pantheon apps

- docs/config/drupal9.md
Drupal 9 was released on June 3, 2020: https://www.drupal.org/docs/understanding-drupal/drupal-9-release-date-and-what-it-means
Removing inaccurate statement from the docs. Also, I just tested and the recipe worked fine for me, so it's possible this entire warning could be deleted too, but was less sure about that. :)
> Drupal 9 is no longer in development

- docs/config/drupal7.md
- docs/config/drupal8.md
- docs/config/drupal9.md
- plugins/lando-recipes/lib/warnings.js
In several places in the docs, there is reference to https://docs.drush.org/en/master/install/, however this page is a 404.
The new location seems to be https://www.drush.org/install/, so updated all instances to that instead.
> Fix broken link to Drush install docs

- integrations/lando-pantheon/lib/pull.js
- integrations/lando-pantheon/scripts/pull.sh
As described in #2568, since v.3.0.8 `lando pull` no longer respects the `--database` option, instead always pulling the `dev` environment's database. This pull request fixes the issue by breaking up the `LANDO_DB_PULL_COMMAND` var into two variables provided by two functions in the js, then re-concatenating them with the `<site.env>` argument between in the shell script. There may be a prettier way to do this with some shell string interpolation trickery, but I could not figure it out.
I am not sure what is the best way to test this, given that it depends on a working Pantheon project with multiple environments.
> Use specified database env in pantheon pull command. lando/lando#2568

- integrations/lando-lagoon/lib/pull.js
- integrations/lando-lagoon/scripts/lagoon-pull.sh
- integrations/lando-lagoon/scripts/lagoon-push.sh
Adds long and short environment name support to lando pull/push within the Lagoon recipe.
```
lando pull --database drupal9-lando-postgres-main --files drupal9-lando-postgres-main
lando push --database drupal9-lando-postgres-main --files drupal9-lando-postgres-main
lando pull --database main --files main
lando push --database main --files main
```
> #2685 Lagoon pull/push support for multiple env name formats

- docs/config/lagoon.md
There is a typo in here: https://docs.lando.dev/config/lagoon.html#pulling-and-pushing-databases-and-files
In the `push` section the command says `pull`.
> Lagoon section - Fix typo

- docs/config/services.md
This PR proposes updates to the Lando documentation
Not relevant:
> Documentation - services.md: type custom is actually compose

- docs/config/redis.md
- plugins/lando-services/services/redis/builder.js
In `plugins/lando-services/services/redis/builder.js` Redis version is defined as `['6', '5', '5.0', '4', '4.0', '2.8']`. This causes an error "redis version 6.0 is not supported" if a user configures their Redis service as `type: redis:6.0`. I suggest matching the docs to code.
> Updated Redis documentation to match code

- contributors.yml
- integrations/lando-platformsh/types/platformsh-appserver/builder.js
The relevant p.sh docs: https://docs.platform.sh/configuration/app/build.html#php-composer-by-default
This fixes #2812.
> Update PATH settings for platform.sh recipe so Composer installed following p.sh's docs is preferred.

- docs/guides/installing-php-extensions-on-lando.md
- examples/php-extensions/Dockerfile.custom
Since version 1.1.11, my `install-php-extensions` script is able to install oci8 (and Oracle Instant Client).
So, what about simplifying the instructions to install it?
> Update instructions for installing PHP extensions

- integrations/lando-lagoon/scripts/lagoon-pull.sh
- Fix problem with hardcoded public file paths in lagoon-pull.sh
- Fix problem with duplicated LANDO_LAGOON_PROJECT in files alias if no database import selected
- Clean up output to prevent flooding the console with irrelevant or duplicative drush output during pull process
- Add additional debug/notice messaging where appropriate
> 2762 - Lagoon Pull - Fix hardcoded public file paths and minor bugs

- docs/config/node.md
- plugins/lando-services/services/node/builder.js
PR adds the ability to set the port option on the node service to false to disable the default port 80 mapping.
Related to #2768 (after more digging, it appeared to be a relatively simple/low-risk feature to add).
> Allow setting node service port to false.

- integrations/lando-lagoon/app.js
Tiny fix as follow up to #2818.
The file is named `.lagoon.yml`, not `lagoon.yml`.
Thanks!
> Fix the filename in the error message.

- docs/config/lemp.md
Figured that in the example, the config files are listed, but they're not used in the lando config.
> Update LEMP example for custom config files

- plugins/lando-services/scripts/install-composer.sh
Prestissimo is only removed on composer branch aliases.
It should support the alternative format as well.
See https://github.com/composer/composer/blob/4e0b8c1/src/Composer/Console/Application.php#L494-L507
> Attempt to remove prestissimo on all composer versions

- docs/config/events.md
The table on the [Events page](https://docs.lando.dev/config/events.html) has some problems in the App column:
- The anchors are wrong (e.g. `app.md#event_pre_destroy` vs. `app.html#pre-destroy`)
- There are no **pre/post-restart** events
- The **ready** event is missing
PR should fix all.
> Fix App Event links

- docs/help/2021-changelog.md
- installer/linux/scripts/postinst
See #2880.  I also took the liberty of moving the chunk of code slightly so that the sudoers-related code would remain colocated.
**EDIT**: This is a very conservative attempt to fix the issue at hand -- there's certainly more I could do, and I'm happy to extend this PR further if desired.
**EDIT 2**: Added some code to further test the writability of the kernel parameter before attempting to write to it, and if it's not writeable, show some explanatory text to the user.
> Compares vm.max_map_count to ideal value before attempting to change it.

- docs/contrib/contrib-testing.md
- examples/drupal7/README.md
- plugins/lando-recipes/types/drupaly/builder.js
In c1298b1b6444e0ce627e005484c750c53ac534cb we introduced a change to the laemp proxy config to allow for the Acquia recipe to inject proxy entries Mailhog. This caused standard Drupal recipes to not inject their own proxy. Other Laempy recipes did not seem to be affected in testing.
> Fixes #2934

- examples/keys/config
- plugins/lando-core/scripts/load-keys.sh
Resolves #2957
With setting `LogLevel=FATAL` the "errors" (which actually isn't an error, as the ssh connection still works) are not outputted by the ssh client.
> use LogLevel=FATAL to hide errors that are actually warnings

- plugins/lando-services/services/solr/builder.js
Possibly fixes #2866 
Issue #2866 seems to be caused by the wrong data directory being set, and that is adjusted using parse8 helper for Solr 8 versions.
I am not sure if there are other places to cover this as well, just spotted the probable cause while looking for a cause / workaround and thought it's at least a starting point.
> Use parse8 helper to set Solr 8.5 and 8.6 options

- docs/config/acquia.md
- experimental/lando-acquia/recipes/acquia/builder.js
- experimental/lando-acquia/recipes/acquia/init.js
This PR updates the Acquia plugin to use the `latest` release of `acli` instead of building from the `master` branch.
> Updated acli to use the latest release instead of master

- docs/config/wordpress.md
- examples/wordpress/README.md
- plugins/lando-recipes/recipes/wordpress/builder.js
Closes #2929 
WordPress now recommends PHP 7.4: https://wordpress.org/about/requirements/
> Use PHP 7.4 for WordPress

- docs/config/lagoon.md
- integrations/lando-lagoon/lib/services.js
- integrations/lando-lagoon/services/lagoon-elasticsearch/builder.js
This PR adds support for Elasticsearch to the Lagoon integration.
I have not provided tests in Lando for this integration (as it is very niche), but we will continue to test in the amazee.io examples for it.
I have updated the docs accordingly to reflect this (and other) service availability in Lando.
I have also updated our core documentation reference to https://docs.lagoon.sh
> Add Elasticsearch support to Lagoon Integration

- docs/contrib/contrib-plugins.md
This PR fixes the core plugins URLs in the documentation.
Not sure if the boxes below are relevant in this case.
> Fix core plugins URLs

- docs/config/drupal9.md
There was a bad link sending you to a 404 in the D9 documentation.
I can only assume this is the location it should be going to, since I can't see what the page used to say...
> Fixing a broken link.

- docs/config/lagoon.md
The lagoon services file moved to `lando/cli` so the link needed updating.
> Update link to lagoon services

- scripts/assemble-win.ps1
Windows installer was getting packaged with mac Docker installer. This fixes that.
Also, a note for future reference, the download path `https://desktop.docker.com/win/stable/...` will become `https://desktop.docker.com/win/main/...` starting with Docker Desktop 4.0.0
> Fixes #3129: Windows package was using Mac Docker Url

- docs/guides/lando-phpstorm.md
This fixes the link in the second paragraph of https://docs.lando.dev/guides/lando-phpstorm.html#debugging-drush-commands to "Debugging Drupal 8 with PHPstorm and Lando on your Mac".
> Fix PHPStorm/Lando debugging broken link

- docs/basics/installation.md
- docs/config/drupal6.md
- docs/config/drupal7.md
- docs/config/joomla.md
- docs/config/lamp.md
- docs/config/laravel.md
- docs/config/lemp.md
- docs/config/wordpress.md
There was a minor typo in the Laravel recipe documentation so I fixed it & updated a few other tiny typos/references (mostly the composer version config example had been copy/pasted from the ````backdrop```` recipe into all other docs without being updated to reflect the page's recipe).
Sorry if this is annoying, was just trying to tidy up as I read.
> Minor typos

- docs/config/node.md
- docs/config/recipes.md
- docs/config/services.md
Here is the corresponding lando-cli pr:
https://github.com/lando/cli/pull/66
> Add support for node 14 and 16, mark older versions as legacy

- installer/win/Lando.iss
Unattended/scripted installations are currently impossible on Windows because message boxes are not suppressible. Msgboxes block the progress of scripted installations. This PR makes them suppressible.
> Make windows installer messages suppressable
